# Generated by Django 4.0.3 on 2022-04-05 22:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamber',
            fields=[
                ('room_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('room_name', models.CharField(max_length=50)),
                ('host_name', models.CharField(max_length=50, unique=True)),
                ('access_guest_pause', models.BooleanField(default=True)),
                ('votes_song_skip', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('max_participant_number', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
