# Generated by Django 4.0.3 on 2022-08-06 16:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_spotify', '0004_alter_spotifyusertoken_spotify_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamber',
            fields=[
                ('chamber_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('chamber_name', models.CharField(max_length=50)),
                ('access_guest_can_pause', models.BooleanField(default=True)),
                ('votes_song_skip', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('max_participant_number', models.IntegerField(default=1)),
                ('is_public', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('song_on_play', models.CharField(blank=True, max_length=50, null=True)),
                ('song_duration', models.IntegerField(blank=True, null=True)),
                ('song_end_at', models.DateTimeField(blank=True, null=True)),
                ('playlist_on_play', models.CharField(blank=True, max_length=50, null=True)),
                ('is_playing', models.BooleanField(default=False)),
                ('host_spotify_id', models.ForeignKey(db_column='host_spotify_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api_spotify.spotifyusertoken', to_field='spotify_id')),
            ],
        ),
        migrations.CreateModel(
            name='ChamberMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_in_chamber', models.BooleanField(default=True)),
                ('chamber_id', models.ForeignKey(db_column='chamber_id', on_delete=django.db.models.deletion.CASCADE, to='api.chamber')),
                ('spotify_id', models.ForeignKey(db_column='spotify_id', on_delete=django.db.models.deletion.CASCADE, to='api_spotify.spotifyusertoken', to_field='spotify_id')),
            ],
        ),
    ]
