# Generated by Django 4.0.3 on 2022-08-06 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_spotify', '0004_alter_spotifyusertoken_spotify_id'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamberMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_in_chamber', models.BooleanField(default=True)),
                ('chamber_id', models.ForeignKey(db_column='chamber_id', on_delete=django.db.models.deletion.CASCADE, to='api.chamber')),
                ('spotify_id', models.ForeignKey(db_column='spotify_id', on_delete=django.db.models.deletion.CASCADE, to='api_spotify.spotifyusertoken', to_field='spotify_id')),
            ],
        ),
    ]
