# Generated by Django 4.0.3 on 2022-04-09 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chamber_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chamber',
            old_name='active',
            new_name='is_active',
        ),
    ]
