# Generated by Django 4.0.3 on 2022-04-13 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_access_guest_pause_chamber_access_guest_can_pause'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chamber',
            old_name='room_id',
            new_name='chamber_id',
        ),
        migrations.RenameField(
            model_name='chamber',
            old_name='room_name',
            new_name='chamber_name',
        ),
    ]
