# Generated by Django 4.0.3 on 2022-05-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_room_id_chamber_chamber_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamber',
            name='song_on_play',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
