# Generated by Django 4.0.3 on 2022-05-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_chamber_song_on_play'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamber',
            name='song_end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
