# Generated by Django 4.0.3 on 2022-07-12 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_chamber_play_list_on_play_chamber_song_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chamber',
            old_name='play_list_on_play',
            new_name='playlist_on_play',
        ),
    ]
