# Generated by Django 4.0.3 on 2022-07-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_play_list_on_play_chamber_playlist_on_play'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamber',
            name='is_playing',
            field=models.BooleanField(default=False),
        ),
    ]
