# Generated by Django 4.0.3 on 2022-04-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_spotify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyusertoken',
            name='access_token',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='spotifyusertoken',
            name='refresh_token',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='spotifyusertoken',
            name='user_session',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
